[ENTITIES.boundaries_left]
    stationary = true
    [ENTITIES.boundaries_left.position2]
        x = -10
        y = -10
    [ENTITIES.boundaries_left.hitbox]
        left = 0
        top = 0
        width = 100
        height = 1000

[ENTITIES.boundaries_top]
    stationary = true
    [ENTITIES.boundaries_top.position2]
        x = -10
        y = -10
    [ENTITIES.boundaries_top.hitbox]
        left = 0
        top = 0
        width = 1000
        height = 100

[ENTITIES.boundaries_right]
    stationary = true
    [ENTITIES.boundaries_right.position2]
        x = 200
        y = -10
    [ENTITIES.boundaries_right.hitbox]
        left = 0
        top = 0
        width = 100
        height = 1000

[ENTITIES.boundaries_bottom]
    stationary = true
    [ENTITIES.boundaries_bottom.position2]
        x = -10
        y = 200
    [ENTITIES.boundaries_bottom.hitbox]
        left = 0
        top = 0
        width = 1000
        height = 100
