[ENTITIES.enemy1]

# PHYSIC
position2 = true
[ENTITIES.enemy1.velocity2]
x = -120
y = 0
[ENTITIES.enemy1.hitbox]
width = 50.0
height = 50.0

# SPEC
[ENTITIES.enemy1.robust]
priority = 10
[ENTITIES.enemy1.health]
amount = 1
[ENTITIES.enemy1.damage]
amount = 1
[ENTITIES.enemy1.team]
name = "mob"
[ENTITIES.enemy1.pattern]
type = 1
amplitude = 75
frequency = 0.2
