[ENTITIES.enemy1]

# PHYSIC
position2 = true
movable = true
[ENTITIES.enemy1.velocity2]
x = -1.0
y = 0
[ENTITIES.enemy1.hitbox]
left = 0.0
top = 0.0
width = 30.0
height = 30.0

# SPEC
[ENTITIES.enemy1.health]
amount = 1
[ENTITIES.enemy1.damage]
amount = 1
[ENTITIES.enemy1.team]
name = "mob"
[ENTITIES.enemy1.pattern]
type = 1
amplitude = 2
frequency = 0.2
