[ENTITIES.player]
player = true
movable = true
position2 = true
    [ENTITIES.player.health]
    amount = 5
    [ENTITIES.player.damage]
    amount = 2
    [ENTITIES.player.team]
    name = "ally"

    [ENTITIES.player.velocity2]
    x = 0.0
    y = 0.0

    [ENTITIES.player.hitbox]
    width = 70.0
    height = 60.0

[ENTITIES.pistol]
position2 = true
    [ENTITIES.pistol.damage]
    amount = 10
    [ENTITIES.pistol.health]
    amount = 10
    [ENTITIES.pistol.team]
    name = "ally"

    [ENTITIES.pistol.velocity2]
    x = 200
    y = 0.0

    [ENTITIES.pistol.fragile]
    priority = 8

    [ENTITIES.pistol.hitbox]
    width = 50.0
    height = 30.0
