[ENTITIES]
    [ENTITIES.player]
    player = true
    movable = true
    position2 = true
        [ENTITIES.player.health]
        amount = 5

        [ENTITIES.player.damage]
        amount = 2

        [ENTITIES.player.team]
        name = "ally"

        [ENTITIES.player.velocity2]
        x = 0.0
        y = 0.0

        [ENTITIES.player.hitbox]
        left = 0.0
        top = 0.0
        width = 30.0
        height = 30.0
    [ENTITIES.projectile]
        position2 = true
            [ENTITIES.projectile.damage]
            amount = 2

            [ENTITIES.projectile.team]
            name = "ally"

            [ENTITIES.projectile.velocity2]
            x = 200
            y = 0.0

            [ENTITIES.projectile.fragile]
            priority = 1

            [ENTITIES.projectile.hitbox]
            left = 0.0
            top = 0.0
            width = 20.0
            height = 10.0
